### ISSUE TITLE
Better handling of fonts that don't allow subsetting

### ISSUE THREAD

**Issue by ediweissmann** [torakiki/sambox#74]
If the font doesn't allow subsetting, just recover from the error and embed the complete font?

```
Caused by: java.io.IOException: This font does not permit subsetting
at org.sejda.sambox.pdmodel.font.TrueTypeEmbedder.subset(TrueTypeEmbedder.java:276)
at org.sejda.sambox.pdmodel.font.PDType0Font.subset(PDType0Font.java:162)
at org.sejda.sambox.pdmodel.PDDocument.writeTo(PDDocument.java:563)
at org.sejda.sambox.pdmodel.PDDocument.writeTo(PDDocument.java:504)
at org.sejda.impl.sambox.component.PDDocumentHandler.savePDDocument(PDDocumentHandler.java:251)
```

**Comment by ediweissmann** [comment]
`PDType0Font load` should default to `embedSubset: false` when the font does not allow subsetting and the user made no explicit choice.

Sample TTF font that does not allow subsetting: https://fonts2u.com/download/solaimanlipinormal.font
