### ISSUE TITLE
The number of options doesn't match the number of widgets

### ISSUE THREAD

**Issue by ediweissmann** [torakiki/sambox#93]
In a document with a checkbox field with one widget but multiple export values with the same actual value:

```
java.lang.IllegalArgumentException: The number of options doesn't match the number of widgets
	at org.sejda.sambox.pdmodel.interactive.form.PDButton.updateByOption(PDButton.java:437)
	at org.sejda.sambox.pdmodel.interactive.form.PDButton.setValue(PDButton.java:162)
```

Seems this exception should not be raised if the export values are the same on the checkbox.

**Comment by ediweissmann** [comment]
In a document with a radio button with one widget but multiple export values which are different:

```
The number of options doesn't match the number of widgets
java.lang.IllegalArgumentException: The number of options doesn't match the number of widgets
	at org.sejda.sambox.pdmodel.interactive.form.PDButton.updateByOption(PDButton.java:446)
	at org.sejda.sambox.pdmodel.interactive.form.PDButton.constructAppearances(PDButton.java:281)
	at org.sejda.sambox.pdmodel.interactive.form.PDTerminalField.applyChange(PDTerminalField.java:172)
	at org.sejda.sambox.pdmodel.interactive.form.PDButton.setValueIgnoreExportOptions(PDButton.java:177)
```

Seems this exception should not be raised if the first value is selected, since the widget exists in that scenario.

One solution would be to raise the exception later on, if no widget matches the supplied value.
